import { Montserrat, Open_Sans } from 'next/font/google';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-montserrat'
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-open-sans'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}${openSans.variable} ${montserrat.variable} antialiased`}
      suppressHydrationWarning
      >
       ff {children}
      </body>
    </html>
  );
}
